import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST || []);

// Cleanup old caches
cleanupOutdatedCaches();

// Take control of all pages immediately
self.addEventListener('activate', (event) => {
    console.log('[SW] v1.3.0 Activated and claiming clients...');
    event.waitUntil(self.clients.claim());
});

self.skipWaiting();
clientsClaim();

// ─── Push Notification Handler ───────────────────────────────────────────────
self.addEventListener('push', (event) => {
    console.log('[SW v1.6.1] Push event received at:', new Date().toISOString());

    let data = {};
    if (event.data) {
        try {
            data = event.data.json();
        } catch (e) {
            data = { body: event.data.text() };
        }
    }

    const title = data.title || 'BudgetWise';
    const options = {
        body: data.body || 'New notification',
        icon: data.icon || '/logo.svg',
        badge: data.badge || '/logo.svg',
        tag: data.tag || 'budgetwise-notification',
        data: data.data || { url: '/' },
        requireInteraction: true,
        renotify: true,
        vibrate: [200, 100, 200],
        actions: data.actions || [],
        // Vital for mobile reliability when app is closed
        timestamp: Date.now()
    };

    // 1. Broadcast to open tabs (foreground)
    const broadcastPromise = self.clients.matchAll({ type: 'window', includeUncontrolled: true })
        .then((windowClients) => {
            windowClients.forEach((client) => {
                client.postMessage({
                    type: 'PUSH_RECEIVED',
                    payload: data,
                    timestamp: new Date().toISOString()
                });
            });
        });

    // 2. Show system notification (background)
    const notificationPromise = self.registration.showNotification(title, options);

    // Ensure service worker stays alive until both actions complete
    event.waitUntil(
        Promise.all([
            broadcastPromise,
            notificationPromise
        ]).catch(err => {
            console.error('[SW] Notification error:', err);
        })
    );
});

// ─── Notification Click Handler ───────────────────────────────────────────────
self.addEventListener('notificationclick', (event) => {
    console.log('[SW] Notification clicked:', event.notification.tag);
    event.notification.close();

    const targetUrl = (event.notification.data && event.notification.data.url) || '/';

    event.waitUntil(
        self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
            // Check if there is already a window/tab open with the target URL
            for (const client of windowClients) {
                if (client.url === targetUrl && 'focus' in client) {
                    return client.focus();
                }
            }
            // If not, open a new window
            if (self.clients.openWindow) {
                return self.clients.openWindow(targetUrl);
            }
        })
    );
});
