import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST || []);

// Cleanup old caches
cleanupOutdatedCaches();

// Take control of all pages immediately
self.skipWaiting();
clientsClaim();

// ─── Push Notification Handler ───────────────────────────────────────────────
self.addEventListener('push', (event) => {
    console.log('[SW] Push received:', event);

    let data = {};
    if (event.data) {
        try {
            data = event.data.json();
        } catch (e) {
            console.log('[SW] Push data is not JSON:', event.data.text());
            data = { body: event.data.text() };
        }
    }

    const title = data.title || 'BudgetWise';
    const options = {
        body: data.body || 'You have a new notification.',
        icon: data.icon || '/logo.svg',
        badge: '/logo.svg',
        tag: data.tag || 'budgetwise-notification',
        data: data.data || { url: '/' },
        requireInteraction: true,
        renotify: true,
        vibrate: [200, 100, 200]
    };

    event.waitUntil(
        self.registration.showNotification(title, options)
    );
});

// ─── Notification Click Handler ───────────────────────────────────────────────
self.addEventListener('notificationclick', (event) => {
    console.log('[SW] Notification clicked:', event.notification.tag);
    event.notification.close();

    const targetUrl = (event.notification.data && event.notification.data.url) || '/';

    event.waitUntil(
        self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
            // Check if there is already a window/tab open with the target URL
            for (const client of windowClients) {
                if (client.url === targetUrl && 'focus' in client) {
                    return client.focus();
                }
            }
            // If not, open a new window
            if (self.clients.openWindow) {
                return self.clients.openWindow(targetUrl);
            }
        })
    );
});
