import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST || []);

// Cleanup old caches
cleanupOutdatedCaches();

// Take control of all pages immediately
self.addEventListener('activate', (event) => {
    console.log('[SW] v1.3.0 Activated and claiming clients...');
    event.waitUntil(self.clients.claim());
});

self.skipWaiting();
clientsClaim();

// ─── Push Notification Handler ───────────────────────────────────────────────
self.addEventListener('push', (event) => {
    console.log('[SW v1.4.0] Push event received');

    let data = {};
    if (event.data) {
        try {
            data = event.data.json();
        } catch (e) {
            data = { body: event.data.text() };
        }
    }

    // Broadcast to all open tabs so the UI can show a debug message
    const broadcastPush = self.clients.matchAll({ type: 'window', includeUncontrolled: true })
        .then((windowClients) => {
            windowClients.forEach((client) => {
                client.postMessage({
                    type: 'PUSH_RECEIVED',
                    payload: data,
                    timestamp: new Date().toISOString()
                });
            });
        });

    const title = data.title || 'BudgetWise';
    const options = {
        body: data.body || 'New notification',
        tag: data.tag || 'budgetwise-test',
        data: data.data || { url: '/' },
        requireInteraction: true,
        renotify: true,
        vibrate: [200, 100, 200]
    };

    event.waitUntil(
        Promise.all([
            broadcastPush,
            self.registration.showNotification(title, options)
        ])
    );
});

// ─── Notification Click Handler ───────────────────────────────────────────────
self.addEventListener('notificationclick', (event) => {
    console.log('[SW] Notification clicked:', event.notification.tag);
    event.notification.close();

    const targetUrl = (event.notification.data && event.notification.data.url) || '/';

    event.waitUntil(
        self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
            // Check if there is already a window/tab open with the target URL
            for (const client of windowClients) {
                if (client.url === targetUrl && 'focus' in client) {
                    return client.focus();
                }
            }
            // If not, open a new window
            if (self.clients.openWindow) {
                return self.clients.openWindow(targetUrl);
            }
        })
    );
});
